In [1]:
from PIL import Image as pimg
import matplotlib.image as img
import numpy as np
from numpy.linalg import eig
import os

In [2]:
# Number of images
n = 40

# All images are of same dimension
# Saving the dimension
image_dimensions = img.imread('images/f1.pgm').shape

# Taking all the images and converting them to 1d array
# Next, append all the array into one array
# Take transpose of this array to get 'F' matrix
image_matrix_list = []
for i in range(1,41):
    image_matrix_list = np.append(image_matrix_list,img.imread(f'images/f{i}.pgm').flatten())
reshaped_matrix = np.reshape(image_matrix_list,(n,image_dimensions[0]*image_dimensions[1]))
image_matrix = reshaped_matrix.T
#print(img.imread('images/f3.pgm').flatten())
#print(reshaped_matrix)

In [3]:
# print(reshaped_matrix[0])
i = np.reshape(reshaped_matrix[0],(image_dimensions[0],image_dimensions[1]))
print(i)
print(reshaped_matrix[0])
a = pimg.fromarray(i)
a.show()
# pimg.fromarray(img.imread('images/f1.pgm'))

[[48. 49. 45. ... 56. 56. 54.]
 [45. 52. 39. ... 52. 50. 51.]
 [45. 50. 42. ... 48. 53. 50.]
 ...
 [50. 48. 50. ... 45. 46. 46.]
 [45. 54. 49. ... 46. 47. 47.]
 [51. 51. 51. ... 47. 46. 46.]]
[48. 49. 45. ... 47. 46. 46.]


In [4]:
# Subtract mean
mean = image_matrix.mean(axis=1,keepdims=True)/40
# print(mean.shape)
# print(mean)
# print(image_matrix.shape)
# print(image_matrix - mean)

# subtracted_mean = image_matrix - mean
F = image_matrix - mean

# print(subtracted_mean.shape)
# tmp = np.reshape(mean,(image_dimensions[0],image_dimensions[1]))
# print()
# print()
# print(tmp)
# print(subtracted_mean)
# a = pimg.fromarray(tmp)
# a.show()

In [5]:
R = np.dot(F,F.T)
print(R)

[[325192.25625    324232.25625    325484.3759375  ... 245961.3540625
  243577.4440625  244869.9890625 ]
 [324232.25625    324008.25625    324912.3759375  ... 245008.3540625
  242937.4440625  244201.9890625 ]
 [325484.3759375  324912.3759375  326297.28701563 ... 245577.20248438
  243322.80598438 244698.60773437]
 ...
 [245961.3540625  245008.3540625  245577.20248438 ... 300052.13201562
  290959.12051562 284726.61476562]
 [243577.4440625  242937.4440625  243322.80598438 ... 290959.12051562
  286132.84501563 279962.70726563]
 [244869.9890625  244201.9890625  244698.60773437 ... 284726.61476562
  279962.70726563 277850.25351562]]


In [6]:
evalue,evector = eig(R)
print(evector)

[[-7.27369159e-03+0.00000000e+00j -1.02099329e-02+0.00000000e+00j
  -2.05398472e-02+0.00000000e+00j ... -1.28520307e-03+3.84393895e-04j
  -6.85034855e-04-7.98821112e-04j -6.85034855e-04+7.98821112e-04j]
 [-7.29774353e-03+0.00000000e+00j -1.02343079e-02+0.00000000e+00j
  -1.96434885e-02+0.00000000e+00j ... -1.05960747e-05+4.51974116e-06j
  -1.98138663e-05-8.76144860e-06j -1.98138663e-05+8.76144860e-06j]
 [-7.31662609e-03+0.00000000e+00j -1.01348485e-02+0.00000000e+00j
  -1.96709933e-02+0.00000000e+00j ... -2.71132391e-05-5.73339090e-05j
  -1.70159133e-04-6.04773802e-05j -1.70159133e-04+6.04773802e-05j]
 ...
 [-6.29781623e-03+0.00000000e+00j  1.17150030e-03+0.00000000e+00j
  -1.63911954e-02+0.00000000e+00j ...  1.04830726e-02+3.95614284e-03j
   1.71397214e-02+1.79961913e-02j  1.71397214e-02-1.79961913e-02j]
 [-6.23265337e-03+0.00000000e+00j -3.95615056e-04+0.00000000e+00j
  -1.42120381e-02+0.00000000e+00j ...  7.72122980e-03-3.99262405e-03j
   1.15352645e-02-2.28364047e-03j  1.15352645e-

In [79]:
print(evector.shape)

(10304, 10304)


In [97]:
# Define k
# k = int(evector.shape[0]*0.1)
k = 5
# k = 10
# print(k)

In [98]:
# print(evector[:,:k].shape)
E = evector[:,:k]

In [99]:
P = np.dot(E.T,F)
print(P)

[[-13416.12283859+0.j -11580.51826348+0.j -11612.6373846 +0.j
  -11861.60451494+0.j -12594.24860606+0.j -12953.41298824+0.j
  -11573.48759764+0.j -12114.36577296+0.j -11214.01419769+0.j
   -9912.96750534+0.j -10856.18083306+0.j -13516.14480236+0.j
  -12680.4503076 +0.j -10942.21429042+0.j -11452.14181118+0.j
  -10630.42814518+0.j -12122.60566137+0.j -13880.43082688+0.j
  -12366.56625944+0.j  -9918.86191858+0.j  -9856.82067901+0.j
   -8690.02588482+0.j -11934.60216303+0.j -10891.72220612+0.j
  -12768.92520609+0.j -12298.33314823+0.j -12286.34914066+0.j
  -11616.69383256+0.j  -8622.93546227+0.j -10561.36415467+0.j
  -10500.61644844+0.j -13310.09997365+0.j  -8937.28024761+0.j
   -9705.58587263+0.j -11629.04950333+0.j -13127.99477407+0.j
  -11666.68207131+0.j -11436.71750165+0.j  -8699.17490259+0.j
   -6246.48439878+0.j]
 [   261.07914406+0.j   1184.03555013+0.j   -221.02448794+0.j
    -756.53761773+0.j    228.1671454 +0.j  -2517.46380777+0.j
   -1305.32012455+0.j   -851.08224594+0.j  -167

In [100]:
P.shape

(5, 40)

In [101]:
E.shape

(10304, 5)

In [102]:
reconstructed_image = np.dot(E,P)
# np.reshape(reconstructed_image.real.T[0],(image_dimensions[0],image_dimensions[1]))

In [103]:
image_index = 1

In [104]:
a = pimg.fromarray(np.reshape(reconstructed_image.real.T[image_index-1],(image_dimensions[0],image_dimensions[1])))
# a.show()
a.convert("L").save(f"output/result_{image_index}_{k}.jpg")

In [105]:
b = pimg.fromarray(img.imread(f'images/f{image_index}.pgm'))
# b.show()
b.convert("L").save(f"output/og_{image_index}_{k}.jpg")